:source-highlighter: coderay
== Installing the Vital AI Development Kit

:sectnums:
:linkattrs:

=== Download the Vital AI Development Kit

After signing up for an account on the http://dashboard.vital.ai[vital.ai dashboard, window="http://dashboard.vital.ai"],   
subscribe to the Vital AI Development Kit (VDK) from the _Products_ page. Under  
_My Products_, you will find downloads for a distribution of the VDK (tar.gz/zip),    
the VDK install script, the VDK uninstall script, VDK documentation, and a vital.ai  
license file which will enable you to use the VDK on your computer. 

=== Install the Vital AI Development Kit

*On Mac OSX, Linux, or Cygwin*

* Download the following:

. VDK distribution (tar.gz/zip) (Do not decompress the distribution)

. VDK install script

. License file

* Set your _VITAL_HOME_ environment variable to a directory on your file system.

* Add _VITAL_HOME/vitalsigns/bin_ and _VITAL_HOME/vitalservice/bin_  
to your _PATH_ environment variable.

_For Mac OSX users, refer to: https://github.com/ersiner/osx-env-sync for information on synchronizing OSX environment variables for command line and GUI applications from a single source. Without this step, GUI applications will not be able to run using the VITAL_HOME environment variable._

* In a terminal window, navigate to the directory into which you downloaded the   
VDK distribution and the VDK install script. 

* Render the VDK install script executable by entering:

[source,sh]
----
chmod u+x ./vdk-install-0.2.302.sh 
----

* Install the VDK in your _VITAL_HOME_ directory by entering:

[source,sh]
----
./vdk-install-0.2.302.sh $VITAL_HOME .  
----

*  Place the downloaded license file into the vital-license directory within   
your _VITAL_HOME_.
  
    
=== Uninstalling the Vital Development Kit

*On Mac OSX, Linux, or Cygwin*

* Download the vdk uninstall script.

* In a terminal window, navigate to the directory into which you downloaded the 
VDK uninstall script.  

* Render the VDK uninstall script executable by entering:

[source,sh]
----
chmod u+x ./vdk-uninstall-0.2.302.sh  
----

* Uninstall the VDK by entering:  

[source,sh]
----
./vdk-uninstall-0.2.302.sh $VITAL_HOME .
----
