this["JST"] = this["JST"] || {};

this["JST"]["templates/footer.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<footer class=\"footer-10\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-sm-3\">\n                <nav>\n                    <h6>Vital AI</h6>\n                    <ul>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/tech.html\">Tech</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/about-us.html\">About Us</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/about-us.html#contact\">Contact</a></li>\n                        <li><a target=\"_blank\" href=\"http://vitalai.com\">Blog</a></li>\n                    </ul>\n                </nav>\n            </div>\n            <div class=\"col-sm-3 col-sm-offset-1\">\n                <nav>\n                    <h6>Products &amp; Services</h6>\n                    <ul>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#download\">Development Kit</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#product\">Software Development</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#product\">Data Science</a></li>\n                    </ul>\n                </nav>\n            </div>\n\n            <div class=\"col-sm-3 col-sm-offset-2\">\n                <nav>\n                    <h6>Resources</h6>\n                    <ul>\n                        <li><a href=\"http://documentation.vital.ai/\">Documentation</a></li>\n                        <li><a target=\"_blank\" href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/discussion-list.html\">Discussion List</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/site/terms-of-service.html\">Terms of Service</a></li>\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/site/privacy-policy.html\">Privacy Policy</a></li>\n                        <!-- <li><a target=_blank href=\"login.html\">Customer Portal Login</a></li> -->\n                        <li><a href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "/mailinglist\">Manage Mailing List Membership</a></li>\n                    </ul>\n                </nav>\n            </div>\n           <center> Copyright © 2016 Vital AI, LLC </center>\n        </div>\n    </div>\n   \n    \n</footer>\n  ";
},"useData":true});

this["JST"]["templates/header.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<!-- header-1 -->\n        <header class=\"header-1\" id=\"main-header\">\n            <div class=\"container\">\n                <div class=\"row\">\n                    <div class=\"navbar col-sm-12 navbar-fixed-top\" role=\"navigation\" style=\"top: -6px;\">\n                        <div class=\"navbar-header\">\n                            <button type=\"button\" class=\"navbar-toggle\"></button>\n                            <a class=\"brand\" href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#home\"><img src=\"img/vitalai_offwhite.png\" style=\"width: auto; height: 25px; margin-top: 6px;\"></a>\n                        </div>\n                        <div class=\"navbar-collapse collapse\">\n                            <ul class=\"nav pull-right\">\n                                <li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#home\">HOME</a>\n			      </li>\n\n<li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/index.html#solutions\">SOLUTIONS</a>\n			      </li>\n			        <li>\n\n				<li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/tech.html\">TECH</a>\n                                </li>\n<li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/about-us.html\">ABOUT US</a>\n			      </li>\n                           \n                                <li>\n                                    <a href=\"http://documentation.vital.ai/\">DOCUMENTATION</a>\n                                </li>\n\n                                <li>\n                                    <a target=\"_blank\" href=\"http://vitalai.com\">BLOG</a>\n                                </li>\n								<li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "\">CONSOLE</a>\n                                </li>\n                               <li style=\"width: 110px\">\n                                 <form class=\"navbar-form pull-left logged-out-visible\">\n                                   <a class=\"btn btn-primary\" href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "/signup\">SIGN UP</a>\n                                 </form>\n                                 <a href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "/myaccount\" class=\"logged-in-visible\"><font class=\"current-email\" size=\"1\">"
    + alias4(((helper = (helper = helpers.email || (depth0 != null ? depth0.email : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"email","hash":{},"data":data}) : helper)))
    + "</font></a>\n                                </li>\n                                <li style=\"width: 120px\">\n                                  <form class=\"navbar-form pull-left\">\n                                    <a class=\"btn btn-info logged-out-visible\" href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "/login\">&nbsp;&nbsp;LOG IN&nbsp;&nbsp;</a>\n									<a id=\"logout-button\" class=\"btn btn-danger logged-in-visible\" href=\""
    + alias4(((helper = (helper = helpers.consoleURL || (depth0 != null ? depth0.consoleURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"consoleURL","hash":{},"data":data}) : helper)))
    + "/logout\">LOG OUT</a>\n                                  </form>\n                                </li>\n                            </ul>\n                            <ul class=\"subnav\">\n                                <li>\n                                    <a href=\"http://documentation.vital.ai/\">Documentation</a>\n                                </li>\n                                <li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/terms-of-service.html\">Terms of Service</a>\n                                </li>\n                                <li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/privacy-policy.html\">Privacy Policy</a>\n                                </li>\n                                <li>\n                                    <a href=\""
    + alias4(((helper = (helper = helpers.vitalSiteURL || (depth0 != null ? depth0.vitalSiteURL : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vitalSiteURL","hash":{},"data":data}) : helper)))
    + "/mailing-list-management.html\">Mailing List Management</a>\n                                </li>\n                            </ul>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </header>\n        ";
},"useData":true});